### ISSUE TITLE
var/run/docker.sock

### ISSUE THREAD

**Issue by eliassal** [sixeyed/pi#1]
Hi, can you please tell me what dos this statement does

volumes:
      - /var/run/docker.sock:/var/run/docker.sock

in jenkins.yaml?
Thanks in advance

**Comment by sixeyed** [comment]
Hi @eliassal - it means Docker commands running inside the container can access the Docker host where the container is running. In this case Jenkins can use the same Docker engine it's running on to build Docker images.

I cover the approach in this YouTube video - https://youtu.be/lO-Lwwy04zs.
