### ISSUE TITLE
Jenkins job Pi Not Found

### ISSUE THREAD

**Issue by jovanz** [sixeyed/pi#2]
Building and Distributing Apps with Docker, Jenkins and Docker Hub exercise have link to Jenkins job PI
![image_2021_03_31T08_43_07_638Z](https://user-images.githubusercontent.com/7665799/113116950-43d28680-920e-11eb-91e9-c7156bf5e827.png)

but when go to link get 
![image_2021_03_31T08_42_52_309Z](https://user-images.githubusercontent.com/7665799/113117134-74b2bb80-920e-11eb-8376-067c88ddfd0d.png)

**Comment by sixeyed** [comment]
Fixed - the underlying `diamol/jenkins` image has been updated, so this was just a rebuild and push. Enjoy the lab :)
